[project]
name = "pvz-cpp"
version = "0.1.0"
description = "PVZ Replication project with C++ and Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.3",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
